name: Run Python Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channel: 'defaults'
          python-version: '3.9'
      - name: Create Conda Environment
        run: conda env create --file environment.yml
      - name: Install dependencies
        run: |
          conda activate <your-conda-environment>
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          conda activate <your-conda-environment>
          pytest
