name: Run Python Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda create --name myenv python=3.9 --yes
          conda activate myenv
          conda install --file requirements.txt --yes
          pip install pytest
          
      - name: Run tests with pytest
        run: pytest